version: "3.8"

services:
  app:
    container_name: angular-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - dummy-products-api-network
    ports:
      - ${ANGULAR_LOCAL_PORT}:${ANGULAR_DOCKER_PORT}

networks:
  dummy-products-api-network:
    driver: bridge
